version: "3.9"

services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "32770:8080"  # host:container
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
