// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GroupServiceDbContext))]
    partial class GroupServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Domain.Entities.DirectMessageGroup", b =>
                {
                    b.Property<string>("User1Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user1_id");

                    b.Property<string>("User2Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user2_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("idx_group");

                    b.ToTable("direct_message_groups", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("GroupAvatar")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("group_avatar");

                    b.Property<string>("GroupDescription")
                        .HasColumnType("text")
                        .HasColumnName("group_description");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_name");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_message_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("GroupId");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_created_by");

                    b.HasIndex("GroupType")
                        .HasDatabaseName("idx_group_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_active");

                    b.ToTable("groups_r", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GroupInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invited_by");

                    b.Property<string>("InvitedUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invited_user");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("InvitationId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("idx_group");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_status");

                    b.ToTable("group_invitations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_muted");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_read_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime")
                        .HasColumnName("left_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DirectMessageGroup", b =>
                {
                    b.HasOne("Domain.Entities.Group", "Group")
                        .WithOne("DirectMessageGroup")
                        .HasForeignKey("Domain.Entities.DirectMessageGroup", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Entities.GroupInvitation", b =>
                {
                    b.HasOne("Domain.Entities.Group", "Group")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("Domain.Entities.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Entities.Group", b =>
                {
                    b.Navigation("DirectMessageGroup");

                    b.Navigation("GroupInvitations");

                    b.Navigation("GroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
